version: '3.8'

volumes:
    postgres:

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminanv
      - POSTGRES_DB=dbo
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    
    #adminer:
    #image: adminer
    #restart: always
    #ports:
    #  - 8080:8080