version: '3.8'

volumes:
    postgres:

services:
  facerecapi:
    container_name: facerecapi
    image: rperes23/facerecapi:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
    restart: always
  
  client:
    container_name: facerecapi-client
    image: rperes23/facerecclient:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "3000:80"
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminanv
      - POSTGRES_DB=dbo
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080